### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by jackitaliano**
# Dark Mode
- add dark mode theme option
- select theme by button in menu
- default theme to change with system theme, override by setting manually
- branched off of theme-sync branch, includes those changes so should merge after

## Screenshots
<div class="flex">
LoggedIn-Darkmode
LoggedIn-Lightmode
</div>

*Logged In Dark vs. Light Mode*

<div class="flex">
LoggedOut-Darkmode
LoggedOut-Lightmode
</div>

*Logged Out Dark vs. Light Mode*

<div class="flex">
MobileChat-Darkmode
MobileSidebar-Darkmode
</div>

*Mobile Dark Mode*

### All svelte files
- remove individually set colors, replace with css vars in `global.css`
- use default css vars (not specific light or dark)

### `global.css`
- add vars for background, border, messages, text, shadow, etc. colors
- add light/dark versions of vars, default to light

### `ThemeSwitcher.svelte`
- Button in Menu
- Handles theme initialization, toggling, and watching system theme for logged in state

### `index.html`
- Add script in body for handling theme initialization in non-logged in state
- Will set theme no matter what is loaded, even if future changes change layout of app

### `Login.svelte`
- Set background of chat (key input) to match background of login regardless of theme set

### CODE REVIEW

**Review by bruffridge — CHANGES_REQUESTED** [review]
Love the dark mode. Just a couple fixes. (tested as PWA in simulator)

1. Make the attachment area background slightly transparent like it was before.
2. Prefer light mode login screen background to be white (bidara logo looks better without white box effect)
3. Bottom of chat window should match the rest of background (white instead of light gray in light mode, black instead of dark gray in dark mode)
4. Blue links are hard to read in dark mode in the intro message

### Before
attach-before
### After
attach-after
### Dark
attach-dark
### Before
login-before
### After
login-after

**Comment by jackitaliano** [comment]
Made the requested changes 👍

**Comment by bruffridge** [comment]
Weren't the popup links white before? I think they were easier to read as white to match dark mode link.

Screenshot 2024-04-09 at 4 12 21 PM

**Comment by jackitaliano** [comment]
@bruffridge 

> Weren't the popup links white before? I think they were easier to read as white to match dark mode link.
> 

Yes, yes they were. I'm not sure why I made them blue, I guess when setting them I just went on autopilot for link colors.

Fixed now.

**Review by bruffridge — APPROVED** [review]

**Pull request merged**
